# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mjl152/Documents/stuff/greplace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mjl152/Documents/stuff/greplace

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mjl152/Documents/stuff/greplace/CMakeFiles /home/mjl152/Documents/stuff/greplace/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mjl152/Documents/stuff/greplace/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named greplace-psearch

# Build rule for target.
greplace-psearch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 greplace-psearch
.PHONY : greplace-psearch

# fast build rule for target.
greplace-psearch/fast:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/build
.PHONY : greplace-psearch/fast

cpu.o: cpu.cpp.o
.PHONY : cpu.o

# target to build an object file
cpu.cpp.o:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/cpu.cpp.o
.PHONY : cpu.cpp.o

cpu.i: cpu.cpp.i
.PHONY : cpu.i

# target to preprocess a source file
cpu.cpp.i:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/cpu.cpp.i
.PHONY : cpu.cpp.i

cpu.s: cpu.cpp.s
.PHONY : cpu.s

# target to generate assembly for a file
cpu.cpp.s:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/cpu.cpp.s
.PHONY : cpu.cpp.s

greplace-psearch-cpu.o: greplace-psearch-cpu.cpp.o
.PHONY : greplace-psearch-cpu.o

# target to build an object file
greplace-psearch-cpu.cpp.o:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/greplace-psearch-cpu.cpp.o
.PHONY : greplace-psearch-cpu.cpp.o

greplace-psearch-cpu.i: greplace-psearch-cpu.cpp.i
.PHONY : greplace-psearch-cpu.i

# target to preprocess a source file
greplace-psearch-cpu.cpp.i:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/greplace-psearch-cpu.cpp.i
.PHONY : greplace-psearch-cpu.cpp.i

greplace-psearch-cpu.s: greplace-psearch-cpu.cpp.s
.PHONY : greplace-psearch-cpu.s

# target to generate assembly for a file
greplace-psearch-cpu.cpp.s:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/greplace-psearch-cpu.cpp.s
.PHONY : greplace-psearch-cpu.cpp.s

greplace-psearch.o: greplace-psearch.cpp.o
.PHONY : greplace-psearch.o

# target to build an object file
greplace-psearch.cpp.o:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/greplace-psearch.cpp.o
.PHONY : greplace-psearch.cpp.o

greplace-psearch.i: greplace-psearch.cpp.i
.PHONY : greplace-psearch.i

# target to preprocess a source file
greplace-psearch.cpp.i:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/greplace-psearch.cpp.i
.PHONY : greplace-psearch.cpp.i

greplace-psearch.s: greplace-psearch.cpp.s
.PHONY : greplace-psearch.s

# target to generate assembly for a file
greplace-psearch.cpp.s:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/greplace-psearch.cpp.s
.PHONY : greplace-psearch.cpp.s

person.o: person.cpp.o
.PHONY : person.o

# target to build an object file
person.cpp.o:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/person.cpp.o
.PHONY : person.cpp.o

person.i: person.cpp.i
.PHONY : person.i

# target to preprocess a source file
person.cpp.i:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/person.cpp.i
.PHONY : person.cpp.i

person.s: person.cpp.s
.PHONY : person.s

# target to generate assembly for a file
person.cpp.s:
	$(MAKE) -f CMakeFiles/greplace-psearch.dir/build.make CMakeFiles/greplace-psearch.dir/person.cpp.s
.PHONY : person.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... greplace-psearch"
	@echo "... rebuild_cache"
	@echo "... cpu.o"
	@echo "... cpu.i"
	@echo "... cpu.s"
	@echo "... greplace-psearch-cpu.o"
	@echo "... greplace-psearch-cpu.i"
	@echo "... greplace-psearch-cpu.s"
	@echo "... greplace-psearch.o"
	@echo "... greplace-psearch.i"
	@echo "... greplace-psearch.s"
	@echo "... person.o"
	@echo "... person.i"
	@echo "... person.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

